# This file defines the config for "ct" (chart tester) used by the helm linting GitHub workflow

# Here we define every possible upstream repo our charts use in `requirements.yaml`
lint-conf: .ci/lint-config.yaml
charts:
  - ".deploy/helm"

check-version-increment: false
