apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $.Chart.Name }}
    labels:
        {{- include "PhantomBot.selectorLabels" $ | nindent 10 }}
spec:
    accessModes: [ {{ .Values.storage.accessModes | default "ReadWriteOnce" | quote }} ]
    {{ if .Values.storage.storageClass }}
    storageClassName: {{ .Values.storage.storageClass }}
    {{ end }}
    resources:
        requests:
            storage: {{ .Values.storage.size }}
