{{- range $name, $claim := .Values.storage.claims }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ $.Chart.Name }}-{{ $name }}
    labels:
        {{- include "PhantomBot.selectorLabels" $ | nindent 10 }}
spec:
    accessModes: [ {{ $claim.accessModes | default $.Values.storage.accessModes | quote }} ]
    storageClassName: {{ $claim.storageClass | default $.Values.storage.storageClass }}
    resources:
        requests:
            storage: {{ $claim.size }}

{{- end }}